@auth = http://localhost:3300/api/auth
@jokes = http://localhost:3300/api/jokes

###
POST {{auth}}/register
Content-Type: application/json

{
  "username": "testDummy",
  "password": "testDummyPassword"
}

###
POST {{auth}}/login
Content-Type: application/json

{
  "username": "testDummy",
  "password": "testDummyPassword"
}

###
GET {{jokes}}
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibG9nZ2VkSW4iOnRydWUsInVzZXJuYW1lIjoidGVzdER1bW15IiwiaWF0IjoxNTY3MjE2NzA1LCJleHAiOjE1NjcyMjAzMDV9.ALyzlweB7rfcJq2-a-ncgyJnM2jXnIdbUosAxIErNRk